name: swift_test_data

services:
  exercises:
    build: .
    volumes:
      - ./:/test_data
      - swift_test_data_build:/test_data/.build
    working_dir: /test_data
    tty: true
    command:
      - -lc
      - |
        echo 'export PS1="🐳 \[\033[1;32m\]\u@:\[\033[1;34m\]\W\[\033[0m\] \$ "' >> /root/.bashrc
        echo 'trap "echo ‼️ You just quit the exercises terminal.; echo To get it back run: docker compose run exercises" EXIT' >> /root/.bashrc
        echo "To run the tests:"
        echo "  swift test"
        exec /bin/bash -l

volumes:
  swift_test_data_build:
